version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=__
      - DB_PASSWORD=__
      - DB_NAME=__
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=__
      - POSTGRES_PASSWORD=__
      - POSTGRES_DB=__
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=__
      - PGADMIN_DEFAULT_PASSWORD=__
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # pgAdmin 설정 데이터를 위한 볼륨 추가
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:    # 새로운 볼륨 정의